version: '3.4'
services:
  test:
    image: steinbock
    build:
      context: ${PWD}
      dockerfile: ${PWD}/Dockerfile
    volumes:
      - ${PWD}/test:/app/steinbock/test
    entrypoint: /bin/bash
    command: ['-c', 'cd /app/steinbock && pip install -r test/requirements.txt && pytest --cov=./ --cov-report=xml']
  debug:
    image: steinbock
    build:
      context: ${PWD}
      dockerfile: ${PWD}/Dockerfile
    volumes:
      - ${PWD}/data:/data:rw
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ~/.Xauthority:/home/steinbock/.Xauthority:ro
    entrypoint: /bin/bash
    command: ['-c', 'pip3 install debugpy -t /tmp && python3 /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 -m steinbock']
    ports:
      - '5678:5678'
    environment:
      - DISPLAY
