version: '3.4'
services:
  steinbock:
    image: ghcr.io/bodenmillergroup/steinbock
    build:
      context: .
      dockerfile: Dockerfile
  test:
    image: ghcr.io/bodenmillergroup/steinbock
    volumes:
      - ./tests:/app/steinbock/tests
    working_dir: /app/steinbock
    entrypoint: /bin/bash
    command: ['-c', 'pip install -r tests/requirements.txt && pip install debugpy -t /tmp && python /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 -m pytest tests']
    user: root
    ports:
      - '5678:5678'
  debug:
    image: ghcr.io/bodenmillergroup/steinbock
    volumes:
      - ./data:/data:rw
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ~/.Xauthority:/home/steinbock/.Xauthority:ro
    environment:
      - DISPLAY
    entrypoint: /bin/bash
    command: ['-c', 'pip install debugpy -t /tmp && python /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 -m steinbock']
    ports:
      - '5678:5678'
