site_name: steinbock

theme:
  name: material
  features:
    - navigation.tabs

markdown_extensions:
  - admonition
  - footnotes

nav:
  - Home:
    - index.md
    - install.md
    - changelog.md
    - license.md
  - CLI usage:
    - cli/introduction.md
    - cli/preprocessing.md
    - cli/classification.md
    - cli/segmentation.md
    - cli/measurement.md
    - cli/tools.md
  - Specifications:
    - specs/file-types.md

