site_name: steinbock
repo_url: https://github.com/BodenmillerGroup/steinbock
site_description: The steinbock toolkit documentation
copyright: University of Zurich
nav:
  - Home:
    - Welcome: index.md
    - Installation:
      - install-docker.md
      - install-python.md
    - Specifications:
      - file-types.md
      - directories.md
    - Development:
      - authors.md
      - contributors.md
      - contributing.md
    - changelog.md
    - license.md
  - Command-line usage:
    - cli/intro.md
    - cli/preprocessing.md
    - cli/classification.md
    - cli/segmentation.md
    - cli/measurement.md
    - cli/visualization.md
    - cli/export.md
    - cli/utils.md
    - cli/apps.md
  - Python usage:
    - python/intro.md
    - API documentation:
      - python/api/steinbock.preprocessing.md
      - python/api/steinbock.classification.md
      - python/api/steinbock.segmentation.md
      - python/api/steinbock.measurement.md
      - python/api/steinbock.visualization.md
      - python/api/steinbock.export.md
      - python/api/steinbock.utils.md
      - python/api/steinbock.io.md
  - Issues: https://github.com/BodenmillerGroup/steinbock/issues
  - Discussions: https://github.com/BodenmillerGroup/steinbock/discussions
theme:
  name: material
  locale: en
  # theme-specific keywords
  logo: img/steinbock-logo-white.png
  favicon: img/steinbock-favicon.png
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.expand
    - navigation.top
    - search.suggest
    - search.highlight
extra_css:
  - mkdocstrings.css
extra:
  version:
    provider: mike
watch:
  - steinbock
markdown_extensions:
  - admonition
  - footnotes
plugins:
  - search: {}
  - mike:
      version_selector: true
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths:
            - steinbock
          options:
            show_root_toc_entry: no
            filters:
              - '!^_'
            show_if_no_docstring: yes
