site_name: steinbock

plugins:
  - mkdocstrings:
      handlers:
        python:
          rendering:
            show_root_toc_entry: no
            show_if_no_docstring: yes
          selection:
            filters:
              - "!^_"
      watch:
        - steinbock
  - mike:
      version_selector: true

markdown_extensions:
  - admonition
  - footnotes

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.top

extra:
  version:
    provider: mike

extra_css:
  - mkdocstrings.css

nav:
  - Home:
    - index.md
    - Getting started:
      - docker.md
      - python.md
    - Specifications:
      - file-types.md
      - directories.md
    - changelog.md
    - license.md
  - CLI usage:
    - cli/intro.md
    - cli/preprocessing.md
    - cli/classification.md
    - cli/segmentation.md
    - cli/measurement.md
    - cli/export.md
    - cli/tools.md
    - cli/apps.md
  - Python usage:
    - python/intro.md
    - API documentation:
      - python/api/steinbock.preprocessing.md
      - python/api/steinbock.classification.md
      - python/api/steinbock.segmentation.md
      - python/api/steinbock.measurement.md
      - python/api/steinbock.export.md
      - python/api/steinbock.tools.md
      - python/api/steinbock.io.md
