[build-system]
requires = ["setuptools>=45", "wheel", "setuptools_scm>=6.2"]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
write_to = "steinbock/_version.py"

[tool.pytest.ini_options]
addopts = "--cov=steinbock --cov-report xml:tests/coverage.xml"
